apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: tyk-cicd-demo-{{ include "httpbin.fullname" . }}
spec:
  contextRef:
    name: tyk-operator-ctx-dev
    namespace: tyk-operator-system
  name: tyk-cicd-demo-{{ include "httpbin.fullname" . }}
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://{{ include "httpbin.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}
    listen_path: {{ .Values.api.listenPath }}
    strip_listen_path: true