apiVersion: kustomize.config.k8s.io/v1beta1

nameSuffix: -staging

secretGenerator:
  - name: tyk-operator-conf
    envs:
    - .env.staging
    literals:
    - TYK_MODE=pro
    - TYK_TLS_INSECURE_SKIP_VERIFY=true

resources:
  - ../base