apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: httpbin-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        url: https://kubernetes.default.svc
      - env: staging
        url: https://kubernetes.default.svc
      - env: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{env}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/caroltyk/tyk-cicd-demo.git'
        path: httpbin
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-{{env}}.yaml
      destination:
        server: '{{url}}'
        namespace: httpbin-app-{{env}}
      syncPolicy:
        automated: {}
